modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Additional-Mods/pickupanimations/issues"
license = "GNU LGPL 3.0"

[[mods]]
modId = "pickupanimations"
version = "${version}"
displayName = "Pickup Animations"
authors = "Dqu1J"
description = '''
Adds a subtle, satisfying animation when picking up items in your inventory.
'''
logoFile = "assets/pickupanimations/icon.png"

[[dependencies.pickupanimations]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pickupanimations]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,26.3)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "pickupanimations.mixins.json"
